//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `JoystickAdapter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __JoystickAdapter_h__
#define __JoystickAdapter_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompJoystickAdapter
{

class JoystickAdapter;
class JoystickAdapterPrx;

}

namespace RoboCompJoystickAdapter
{

struct AxisParams
{
    ::std::string name;
    float value;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&, const float&> ice_tuple() const
    {
        return std::tie(name, value);
    }
};

struct ButtonParams
{
    ::std::string name;
    int step;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&, const int&> ice_tuple() const
    {
        return std::tie(name, step);
    }
};

using AxisList = ::std::vector<AxisParams>;

using ButtonsList = ::std::vector<ButtonParams>;

struct TData
{
    ::std::string id;
    ::RoboCompJoystickAdapter::AxisList axes;
    ::RoboCompJoystickAdapter::ButtonsList buttons;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&, const ::RoboCompJoystickAdapter::AxisList&, const ::RoboCompJoystickAdapter::ButtonsList&> ice_tuple() const
    {
        return std::tie(id, axes, buttons);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompJoystickAdapter
{

class JoystickAdapter : public virtual ::Ice::Object
{
public:

    using ProxyType = JoystickAdapterPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void sendData(TData data, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_sendData(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompJoystickAdapter
{

class JoystickAdapterPrx : public virtual ::Ice::Proxy<JoystickAdapterPrx, ::Ice::ObjectPrx>
{
public:

    void sendData(const TData& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &JoystickAdapterPrx::_iceI_sendData, data, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto sendDataAsync(const TData& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &JoystickAdapterPrx::_iceI_sendData, data, context);
    }

    ::std::function<void()>
    sendDataAsync(const TData& data,
                  ::std::function<void()> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(std::move(response), std::move(ex), std::move(sent), this, &RoboCompJoystickAdapter::JoystickAdapterPrx::_iceI_sendData, data, context);
    }

    /// \cond INTERNAL
    void _iceI_sendData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const TData&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    JoystickAdapterPrx() = default;
    friend ::std::shared_ptr<JoystickAdapterPrx> IceInternal::createProxy<JoystickAdapterPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::RoboCompJoystickAdapter::AxisParams>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompJoystickAdapter::AxisParams, S>
{
    static void read(S* istr, ::RoboCompJoystickAdapter::AxisParams& v)
    {
        istr->readAll(v.name, v.value);
    }
};

template<>
struct StreamableTraits<::RoboCompJoystickAdapter::ButtonParams>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompJoystickAdapter::ButtonParams, S>
{
    static void read(S* istr, ::RoboCompJoystickAdapter::ButtonParams& v)
    {
        istr->readAll(v.name, v.step);
    }
};

template<>
struct StreamableTraits<::RoboCompJoystickAdapter::TData>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 3;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompJoystickAdapter::TData, S>
{
    static void read(S* istr, ::RoboCompJoystickAdapter::TData& v)
    {
        istr->readAll(v.id, v.axes, v.buttons);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompJoystickAdapter
{

using JoystickAdapterPtr = ::std::shared_ptr<JoystickAdapter>;
using JoystickAdapterPrxPtr = ::std::shared_ptr<JoystickAdapterPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompJoystickAdapter
{

class JoystickAdapter;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< JoystickAdapter>&);
::IceProxy::Ice::Object* upCast(JoystickAdapter*);
/// \endcond

}

}

namespace RoboCompJoystickAdapter
{

class JoystickAdapter;
/// \cond INTERNAL
::Ice::Object* upCast(JoystickAdapter*);
/// \endcond
typedef ::IceInternal::Handle< JoystickAdapter> JoystickAdapterPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompJoystickAdapter::JoystickAdapter> JoystickAdapterPrx;
typedef JoystickAdapterPrx JoystickAdapterPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(JoystickAdapterPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompJoystickAdapter
{

struct AxisParams
{
    ::std::string name;
    ::Ice::Float value;
};

struct ButtonParams
{
    ::std::string name;
    ::Ice::Int step;

    bool operator==(const ButtonParams& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(name != rhs_.name)
        {
            return false;
        }
        if(step != rhs_.step)
        {
            return false;
        }
        return true;
    }

    bool operator<(const ButtonParams& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(name < rhs_.name)
        {
            return true;
        }
        else if(rhs_.name < name)
        {
            return false;
        }
        if(step < rhs_.step)
        {
            return true;
        }
        else if(rhs_.step < step)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const ButtonParams& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const ButtonParams& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const ButtonParams& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const ButtonParams& rhs_) const
    {
        return !operator<(rhs_);
    }
};

typedef ::std::vector<AxisParams> AxisList;

typedef ::std::vector<ButtonParams> ButtonsList;

struct TData
{
    ::std::string id;
    ::RoboCompJoystickAdapter::AxisList axes;
    ::RoboCompJoystickAdapter::ButtonsList buttons;
};

}

namespace RoboCompJoystickAdapter
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 * Create a wrapper instance by calling ::RoboCompJoystickAdapter::newCallback_JoystickAdapter_sendData.
 */
class Callback_JoystickAdapter_sendData_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_JoystickAdapter_sendData_Base> Callback_JoystickAdapter_sendDataPtr;

}

namespace IceProxy
{

namespace RoboCompJoystickAdapter
{

class JoystickAdapter : public virtual ::Ice::Proxy<JoystickAdapter, ::IceProxy::Ice::Object>
{
public:

    void sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_sendData(_iceI_begin_sendData(data, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_sendData(data, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendData(data, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendData(data, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::RoboCompJoystickAdapter::TData& data, const ::RoboCompJoystickAdapter::Callback_JoystickAdapter_sendDataPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendData(data, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context& context, const ::RoboCompJoystickAdapter::Callback_JoystickAdapter_sendDataPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendData(data, context, cb, cookie);
    }

    void end_sendData(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_sendData(const ::RoboCompJoystickAdapter::TData&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompJoystickAdapter
{

class JoystickAdapter : public virtual ::Ice::Object
{
public:

    typedef JoystickAdapterPrx ProxyType;
    typedef JoystickAdapterPtr PointerType;

    virtual ~JoystickAdapter();

#ifdef ICE_CPP11_COMPILER
    JoystickAdapter() = default;
    JoystickAdapter(const JoystickAdapter&) = default;
    JoystickAdapter& operator=(const JoystickAdapter&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void sendData(const TData& data, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_sendData(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const JoystickAdapter& lhs, const JoystickAdapter& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const JoystickAdapter& lhs, const JoystickAdapter& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompJoystickAdapter::AxisParams>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompJoystickAdapter::AxisParams, S>
{
    static void write(S* ostr, const ::RoboCompJoystickAdapter::AxisParams& v)
    {
        ostr->write(v.name);
        ostr->write(v.value);
    }
};

template<typename S>
struct StreamReader< ::RoboCompJoystickAdapter::AxisParams, S>
{
    static void read(S* istr, ::RoboCompJoystickAdapter::AxisParams& v)
    {
        istr->read(v.name);
        istr->read(v.value);
    }
};

template<>
struct StreamableTraits< ::RoboCompJoystickAdapter::ButtonParams>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompJoystickAdapter::ButtonParams, S>
{
    static void write(S* ostr, const ::RoboCompJoystickAdapter::ButtonParams& v)
    {
        ostr->write(v.name);
        ostr->write(v.step);
    }
};

template<typename S>
struct StreamReader< ::RoboCompJoystickAdapter::ButtonParams, S>
{
    static void read(S* istr, ::RoboCompJoystickAdapter::ButtonParams& v)
    {
        istr->read(v.name);
        istr->read(v.step);
    }
};

template<>
struct StreamableTraits< ::RoboCompJoystickAdapter::TData>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 3;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompJoystickAdapter::TData, S>
{
    static void write(S* ostr, const ::RoboCompJoystickAdapter::TData& v)
    {
        ostr->write(v.id);
        ostr->write(v.axes);
        ostr->write(v.buttons);
    }
};

template<typename S>
struct StreamReader< ::RoboCompJoystickAdapter::TData, S>
{
    static void read(S* istr, ::RoboCompJoystickAdapter::TData& v)
    {
        istr->read(v.id);
        istr->read(v.axes);
        istr->read(v.buttons);
    }
};

}
/// \endcond

namespace RoboCompJoystickAdapter
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 * Create a wrapper instance by calling ::RoboCompJoystickAdapter::newCallback_JoystickAdapter_sendData.
 */
template<class T>
class CallbackNC_JoystickAdapter_sendData : public Callback_JoystickAdapter_sendData_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_JoystickAdapter_sendData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoystickAdapter_sendData<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoystickAdapter_sendData<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoystickAdapter_sendData<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoystickAdapter_sendData<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 * Create a wrapper instance by calling ::RoboCompJoystickAdapter::newCallback_JoystickAdapter_sendData.
 */
template<class T, typename CT>
class Callback_JoystickAdapter_sendData : public Callback_JoystickAdapter_sendData_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_JoystickAdapter_sendData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T, typename CT> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoystickAdapter_sendData<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T, typename CT> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoystickAdapter_sendData<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T, typename CT> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoystickAdapter_sendData<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData.
 */
template<class T, typename CT> Callback_JoystickAdapter_sendDataPtr
newCallback_JoystickAdapter_sendData(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoystickAdapter_sendData<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
