//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `YoloObjects.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <YoloObjects.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompYoloObjects_YoloObjects_ids[2] =
{
    "::Ice::Object",
    "::RoboCompYoloObjects::YoloObjects"
};
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_ops[] =
{
    "getImage",
    "getYoloJointData",
    "getYoloObjectNames",
    "getYoloObjects",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getImage_name = "getImage";
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name = "getYoloJointData";
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name = "getYoloObjectNames";
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name = "getYoloObjects";

}

bool
RoboCompYoloObjects::YoloObjects::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompYoloObjects_YoloObjects_ids, iceC_RoboCompYoloObjects_YoloObjects_ids + 2, s);
}

::std::vector<::std::string>
RoboCompYoloObjects::YoloObjects::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompYoloObjects_YoloObjects_ids[0], &iceC_RoboCompYoloObjects_YoloObjects_ids[2]);
}

::std::string
RoboCompYoloObjects::YoloObjects::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompYoloObjects::YoloObjects::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompYoloObjects::YoloObjects";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getImage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::RoboCompCameraRGBDSimple::TImage ret = this->getImage(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getYoloJointData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TJointData ret = this->getYoloJointData(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getYoloObjectNames(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TObjectNames ret = this->getYoloObjectNames(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getYoloObjects(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TData ret = this->getYoloObjects(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompYoloObjects_YoloObjects_ops, iceC_RoboCompYoloObjects_YoloObjects_ops + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompYoloObjects_YoloObjects_ops)
    {
        case 0:
        {
            return _iceD_getImage(in, current);
        }
        case 1:
        {
            return _iceD_getYoloJointData(in, current);
        }
        case 2:
        {
            return _iceD_getYoloObjectNames(in, current);
        }
        case 3:
        {
            return _iceD_getYoloObjects(in, current);
        }
        case 4:
        {
            return _iceD_ice_id(in, current);
        }
        case 5:
        {
            return _iceD_ice_ids(in, current);
        }
        case 6:
        {
            return _iceD_ice_isA(in, current);
        }
        case 7:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompYoloObjects::YoloObjectsPrx::_iceI_getImage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraRGBDSimple::TImage>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getImage_name);
    outAsync->invoke(iceC_RoboCompYoloObjects_YoloObjects_getImage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompYoloObjects::YoloObjectsPrx::_iceI_getYoloJointData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompYoloObjects::TJointData>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name);
    outAsync->invoke(iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompYoloObjects::YoloObjectsPrx::_iceI_getYoloObjectNames(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompYoloObjects::TObjectNames>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name);
    outAsync->invoke(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompYoloObjects::YoloObjectsPrx::_iceI_getYoloObjects(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompYoloObjects::TData>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name);
    outAsync->invoke(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompYoloObjects::YoloObjectsPrx::_newInstance() const
{
    return ::IceInternal::createProxy<YoloObjectsPrx>();
}
/// \endcond

const ::std::string&
RoboCompYoloObjects::YoloObjectsPrx::ice_staticId()
{
    return YoloObjects::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getImage_name = "getImage";

const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name = "getYoloJointData";

const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name = "getYoloObjectNames";

const ::std::string iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name = "getYoloObjects";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompYoloObjects::upCast(YoloObjects* p) { return p; }

void
::IceProxy::RoboCompYoloObjects::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< YoloObjects>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new YoloObjects;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompYoloObjects::YoloObjects::_iceI_begin_getImage(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getImage_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompYoloObjects_YoloObjects_getImage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompYoloObjects_YoloObjects_getImage_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompYoloObjects_YoloObjects_getImage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompCameraRGBDSimple::TImage
IceProxy::RoboCompYoloObjects::YoloObjects::end_getImage(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompYoloObjects_YoloObjects_getImage_name);
    ::RoboCompCameraRGBDSimple::TImage ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompYoloObjects::YoloObjects::_iceI_begin_getYoloJointData(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompYoloObjects::TJointData
IceProxy::RoboCompYoloObjects::YoloObjects::end_getYoloJointData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompYoloObjects_YoloObjects_getYoloJointData_name);
    ::RoboCompYoloObjects::TJointData ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompYoloObjects::YoloObjects::_iceI_begin_getYoloObjectNames(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompYoloObjects::TObjectNames
IceProxy::RoboCompYoloObjects::YoloObjects::end_getYoloObjectNames(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompYoloObjects_YoloObjects_getYoloObjectNames_name);
    ::RoboCompYoloObjects::TObjectNames ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompYoloObjects::YoloObjects::_iceI_begin_getYoloObjects(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompYoloObjects::TData
IceProxy::RoboCompYoloObjects::YoloObjects::end_getYoloObjects(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompYoloObjects_YoloObjects_getYoloObjects_name);
    ::RoboCompYoloObjects::TData ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompYoloObjects::YoloObjects::_newInstance() const
{
    return new YoloObjects;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompYoloObjects::YoloObjects::ice_staticId()
{
    return ::RoboCompYoloObjects::YoloObjects::ice_staticId();
}

RoboCompYoloObjects::YoloObjects::~YoloObjects()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompYoloObjects::upCast(YoloObjects* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_ids[2] =
{
    "::Ice::Object",
    "::RoboCompYoloObjects::YoloObjects"
};

}

bool
RoboCompYoloObjects::YoloObjects::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompYoloObjects_YoloObjects_ids, iceC_RoboCompYoloObjects_YoloObjects_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompYoloObjects::YoloObjects::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompYoloObjects_YoloObjects_ids[0], &iceC_RoboCompYoloObjects_YoloObjects_ids[2]);
}

const ::std::string&
RoboCompYoloObjects::YoloObjects::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompYoloObjects::YoloObjects::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompYoloObjects::YoloObjects";
    return typeId;
#else
    return iceC_RoboCompYoloObjects_YoloObjects_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getImage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::RoboCompCameraRGBDSimple::TImage ret = this->getImage(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getYoloJointData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TJointData ret = this->getYoloJointData(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getYoloObjectNames(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TObjectNames ret = this->getYoloObjectNames(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceD_getYoloObjects(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TData ret = this->getYoloObjects(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompYoloObjects_YoloObjects_all[] =
{
    "getImage",
    "getYoloJointData",
    "getYoloObjectNames",
    "getYoloObjects",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompYoloObjects::YoloObjects::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompYoloObjects_YoloObjects_all, iceC_RoboCompYoloObjects_YoloObjects_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompYoloObjects_YoloObjects_all)
    {
        case 0:
        {
            return _iceD_getImage(in, current);
        }
        case 1:
        {
            return _iceD_getYoloJointData(in, current);
        }
        case 2:
        {
            return _iceD_getYoloObjectNames(in, current);
        }
        case 3:
        {
            return _iceD_getYoloObjects(in, current);
        }
        case 4:
        {
            return _iceD_ice_id(in, current);
        }
        case 5:
        {
            return _iceD_ice_ids(in, current);
        }
        case 6:
        {
            return _iceD_ice_isA(in, current);
        }
        case 7:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompYoloObjects::YoloObjects::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< YoloObjects, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompYoloObjects::YoloObjects::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< YoloObjects, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompYoloObjects::_icePatchObjectPtr(YoloObjectsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = YoloObjectsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(YoloObjects::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
